tasks:
  - command: git config --global user.email "5112707+Hapattaja@users.noreply.github.com"
  - command: pip3 install -U platformio && platformio run

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
